- name: Build Azure SignalR Sample
  hosts: linux 
  vars:
    azure_signalr_sample_home: "/home/{{ansible_ssh_user}}/signalr-bench/AzureSignalRChatSample/"
  tasks:
    - name: "Build Azure SignalR Sample"
      shell: |
        cd "{{azure_signalr_sample_home}}"
        "./build.sh" 
