- hosts: linux
  tasks:
  - replace:
      dest: /home/{{ansible_user}}/signalr-bench/AzureSignalRChatSample/ChatSample/Properties/launchSettings.json
      regexp: 'localhost'
      replace: "{{ansible_host}}"
      backup: yes
