- hosts: linux
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - sysctl:
      name: net.core.somaxconn
      value: 32768
      state: present
  - sysctl:
      name: fs.file-max
      value: 655350
      state: present
  - sysctl:
      name: net.ipv4.ip_local_port_range
      value: "2000 65535"
      state: present
